blank_issues_enabled: false
contact_links:
  - name: Usage Questions
    url: https://github.com/CongressionalInsights/theworkshop/discussions
    about: Ask how-to questions in Discussions.
  - name: Security Reports
    url: https://github.com/CongressionalInsights/theworkshop/security/advisories
    about: Report vulnerabilities privately.
